meta_product_name: "Cup Of Sugar"
meta_title: "Cup Of Sugar - Lend to and borrow from your neighbours"
meta_description: "Lend to and borrow items from your neighbours"
meta_image: "cupofsugar_cover_image.png" # should exist in `app/assets/images/`
